// Generated by CoffeeScript 1.8.0
(function() {
  describe("When a project exists", function() {
    var project;
    project = null;
    beforeEach(function() {
      return project = new Deventure.Project();
    });
    it("Has a list of team members", function() {
      return expect(project.teamMembers.isArray);
    });
    return describe("When addTeamMember is called with a new person", function() {
      beforeEach(function() {
        return project.addTeamMember({});
      });
      it("Should add that person to the teamMembers array", function() {
        return expect(project.teamMembers.length).toEqual(1);
      });
      return describe("When getStatus() is called on the project", function() {
        var result;
        result = null;
        beforeEach(function() {
          return result = project.getStatus();
        });
        it("Returns a JavaScript object", function() {
          return expect(result).toBeDefined();
        });
        return it("Returns a 0 project completion status", function() {
          return expect(result.completionPercentage).toEqual(0);
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=projectSpecs.js.map
